apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-project
  annotations:
    github.com/project-slug: bcdr-demos/python-project
    coder.com/template: "devcontainers"
    coder.com/parameter/repo: "custom"
    coder.com/parameter/repo_url: "https://github.com/bcdr-demos/python-project"
    coder.com/parameter/region: "us-pittsburgh"
    coder.com/create-mode: "auto"
spec:
  type: other
  lifecycle: unknown
  owner: pm
